[package]
name = "hello-triangle"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.11.3"
pollster = "0.3.0"
wgpu = "0.19.4"
winit = "0.29.15"
